// src/scripts/config.js

/**
 * 디바이스별 UPPERDATE 좌표 분리 애니메이션 시스템의 모든 설정 상수
 */
export const DYNAMIC_BLACK_ANIMATION_CONFIG = {
  APPLEWATCH_SCALE_ANIMATION: {
    AT_ANIMATION_START: 4.0,
    AT_ANIMATION_END: 1.0,
  },

  DYNAMIC_BLACK_MOBILE_APPLEWATCH_CASE_ANIMATION: {
    SCALE_AT_ANIMATION_START: 1.1,
    SCALE_AT_ANIMATION_END: 1.0,
    FADE_ANIMATION_COMPLETE_AT_PROGRESS: 0.2,
    DYNAMIC_BLACK_START_AT_PROGRESS: 0.1,
    SCALE_ANIMATION_START_AT_PROGRESS: 0.6,
    ROTATION_MAX_DEGREES: 1.5,
    APPLE_WATCH_TRANSFORM_START_AT_PROGRESS: 0.8,
  },

  ANIMATION_TRIGGER_THRESHOLDS: {
    APPLEWATCH_COMPLICATIONS_APPEAR_AT_PROGRESS: 0.2,
    DESKTOP_APPLEWATCH_MOVE_START_AT_PROGRESS: 0.7,
    PRODUCTTEXT_DOM_APPEAR_AT_PROGRESS: 0.85,
    DESKTOP_DYNAMIC_BLACK_START_AT_PROGRESS: 0.1,
    DESKTOP_APPLE_WATCH_TRANSFORM_START_AT_PROGRESS: 0.8,
  },

  RESPONSIVE_DEVICE_BREAKPOINTS: {
    MOBILE_DEVICE_MAX_WIDTH_PIXELS: 768,
    SMALL_MOBILE_DEVICE_MAX_WIDTH_PIXELS: 375,
    DESKTOP_DEVICE_MIN_WIDTH_PIXELS: 769,
  },

  ANIMATION_DURATION_SETTINGS: {
    SCROLL_TRIGGER_SCRUB_DELAY_SECONDS: 0.3,
    CSS_TRANSITION_DURATION_SECONDS: 0.8,
    BORDER_RADIUS_TRANSITION_SECONDS: 0.8,
  },

  SCROLL_HEIGHT_CALCULATION: {
    SCROLL_END_POINT_HEIGHT_MULTIPLIER: 0.8,
    REFERENCE_ASPECT_RATIO_WIDTH: 16,
    REFERENCE_ASPECT_RATIO_HEIGHT: 9,
    REFERENCE_SCREEN_WIDTH_PIXELS: 1920,
    REFERENCE_SCREEN_HEIGHT_PIXELS: 1080,
    MINIMUM_SECTION_HEIGHT_PIXELS: 800,
  },

  DESKTOP_APPLEWATCH_MOVEMENT: {
    MOVE_DISTANCE_MULTIPLIER: 0.35,
    EASING_CURVE_THRESHOLD: 0.5,
  },

  APPLEWATCH_COMPLICATIONS_ANIMATION: {
    UPPERDATE_DESKTOP_INITIAL_X_OFFSET_PIXELS: 0,
    UPPERDATE_DESKTOP_INITIAL_Y_OFFSET_PIXELS: -30,
    UPPERDATE_MOBILE_INITIAL_X_OFFSET_PIXELS: 0,
    UPPERDATE_MOBILE_INITIAL_Y_OFFSET_PIXELS: -30,
    UPPERDATE_SMALL_MOBILE_INITIAL_X_OFFSET_PIXELS: 0,
    UPPERDATE_SMALL_MOBILE_INITIAL_Y_OFFSET_PIXELS: -30,
    UPPERDATE_FADE_IN_DURATION_PROGRESS: 0.25,
  },

  PRODUCTTEXT_DOM_ANIMATION: {
    INITIAL_SCALE: 0.7,
    FINAL_SCALE: 1.0,
    INITIAL_Y_OFFSET_PIXELS: 40,
    DESKTOP_INITIAL_X_OFFSET_PIXELS: -100,
    FADE_IN_DURATION_PROGRESS: 0.15,
  },

  DYNAMIC_BLACK_COLORS: {
    BASE_BLACK: '#000000',
    MIDNIGHT: '#1c1c1e',
    SPACE_GRAY: '#2c2c2e',
    GLOSSY_BLACK: '#0a0a0a',
    DEEP_BLACK: '#050505',
  },

  APPLE_WATCH_TRANSFORMATION: {
    CROWN_OPACITY_START: 0,
    CROWN_OPACITY_END: 1,
    BUTTON_OPACITY_START: 0,
    BUTTON_OPACITY_END: 1,
    BAND_OPACITY_START: 0,
    BAND_OPACITY_END: 1,
    TRANSFORMATION_DURATION_PROGRESS: 0.2,
  },

  RESPONSIVE_START_POINTS: {
    SMALL_MOBILE_START: 'bottom-=200px top',
    MOBILE_START: 'bottom-=100px top',
    DESKTOP_START: 'bottom top',
  },
};
